---
# tasks file for nserver role
#
- name: Stop NM managing DNS for Server
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
- name: Change resolv.conf file for ENV01
  template:
    src: "../templates/nserver.config2.j2"
    dest: "/etc/resolv.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "yes"
  become: true
- name: Set resolv.conf immutable.
  file:
    path: "/etc/resolv.conf"
    attr: i
  become: true
